version: "3"
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    ports:
     - "5432:5432"

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  db_admin:
    image: dpage/pgadmin4:${PG_ADMIN_VERSION}
    ports:
      - "${PG_ADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    volumes:
      - ./config/pgadmin_servers.json:/pgadmin4/servers.json
